name: Windows Build

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        git clone --depth 1 --recursive -b 1.10-dev https://github.com/alliedmodders/sourcemod.git
        powershell -noprofile -executionpolicy bypass -file .\sourcemod\tools\checkout-deps.ps1
      
    - name: Build
      run: |
        mkdir build
        cd build
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"
        python ../configure.py --sdks present --enable-optimize
        ambuild
      shell: cmd
              
    - name: Upload
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: LoadSoundScript-windows-${{github.run_number}}
        path: ${{github.workspace}}/build/loadsoundscript
