name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Packages
      run: sudo apt-get install libc6-dev-i386 g++-multilib
    
    - name: Install Dependencies
      run: |
        git clone --depth 1 --recursive -b 1.12-dev https://github.com/alliedmodders/sourcemod.git
        cp -R ./sourcemod/hl2sdk-manifests ./
        ./sourcemod/tools/checkout-deps.sh
      
    - name: Build
      run: |
        mkdir build && cd build
        python ../configure.py --sdks tf2 --enable-optimize
        ~/.local/bin/ambuild
              
    - name: Upload
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: LoadSoundScript-linux-${{github.run_number}}
        path: ${{github.workspace}}/build/loadsoundscript
  
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
  
    - uses: actions/setup-python@v5
      name: Setup Python 3.8
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install Dependencies
      run: |
        git clone --depth 1 --recursive -b 1.12-dev https://github.com/alliedmodders/sourcemod.git
        powershell -noprofile -executionpolicy bypass -file .\sourcemod\tools\checkout-deps.ps1
        #robocopy sourcemod\hl2sdk-manifests . /e & exit 0
      
    - name: Build
      run: |
        mkdir build
        cd build
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"
        python ../configure.py --sdks tf2 --enable-optimize --hl2sdk-manifest-path=..\..\sourcemod\hl2sdk-manifests
        ambuild
      shell: cmd
              
    - name: Upload
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: LoadSoundScript-windows-${{github.run_number}}
        path: ${{github.workspace}}/build/loadsoundscript
